CREATE DATABASE IF NOT EXISTS casodois;
USE casodois;

CREATE TABLE IF NOT EXISTS Passageiros (
    PassageiroID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    Telefone VARCHAR(14),
    Endereco VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Voos (
    VooID INT AUTO_INCREMENT PRIMARY KEY,
    CodigoVoo VARCHAR(10) NOT NULL UNIQUE,
    Origem VARCHAR(100) NOT NULL,
    Destino VARCHAR(100) NOT NULL,
    HorarioPartida DATETIME NOT NULL,
    HorarioChegada DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Aeroportos (
    AeroportoID INT AUTO_INCREMENT PRIMARY KEY,
    CodigoAeroporto VARCHAR(10) NOT NULL UNIQUE,
    Nome VARCHAR(100) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Estado VARCHAR(100) NOT NULL,
    Pais VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Aeronaves (
    AeronaveID INT AUTO_INCREMENT PRIMARY KEY,
    Identificador VARCHAR(50) NOT NULL UNIQUE,
    Modelo VARCHAR(100) NOT NULL,
    Capacidade INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Funcionarios (
    FuncionarioID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Identificador VARCHAR(50) NOT NULL UNIQUE,
    Funcao VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Reservas (
    ReservaID INT AUTO_INCREMENT PRIMARY KEY,
    PassageiroID INT,
    VooID INT,
    DataReserva DATETIME NOT NULL,
    FOREIGN KEY (PassageiroID) REFERENCES Passageiros(PassageiroID),
    FOREIGN KEY (VooID) REFERENCES Voos(VooID)
);

CREATE TABLE IF NOT EXISTS OperacoesVoo (
    OperacaoID INT AUTO_INCREMENT PRIMARY KEY,
    VooID INT,
    FuncionarioID INT,
    FOREIGN KEY (VooID) REFERENCES Voos(VooID),
    FOREIGN KEY (FuncionarioID) REFERENCES Funcionarios(FuncionarioID)
);
